<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Path to the build manifest
    |--------------------------------------------------------------------------
    |
    | This is the path to the manifest file generated by Vite when you run
    | the "npm run build" command. By default, this file lives in the
    | "public/build" directory.
    |
    */

    'manifest' => public_path('build/manifest.json'),

    /*
    |--------------------------------------------------------------------------
    | Dev Server
    |--------------------------------------------------------------------------
    |
    | Here you can control whether the dev server should be used. In your
    | production environment you should set this to false so Laravel
    | always loads the versioned build assets instead.
    |
    */

    'dev_server' => [
        'enabled' => false,
        'url' => 'http://localhost:5173',
    ],

];

